[package]
name = "idn-contracts"
version = "0.1.0"
edition = "2024"

[dependencies]
ink = { version = "5.1.1", default-features = false }
codec = { package = "parity-scale-codec", version = "3.7.4", default-features = false, features = ["derive"] }
scale-info = { version = "2.11.6", default-features = false, features = ["derive"] }
sha2 = { version = "0.10.8", default-features = false }
sp-idn-traits = { path = "../../primitives/traits", default-features = false }
bp-idn = { path = "../../chains/ideal-network/bridge", default-features = false }
pallet-randomness-beacon = { path = "../../pallets/randomness-beacon", default-features = false }

[dev-dependencies]
serde = { version = "1.0", optional = false }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "parity-scale-codec/std",
    "scale-info/std",
    "sha2/std",
    "sp-idn-traits/std",
    "bp-idn/std",
]
