[package]
name = "noise"
version = "0.1.0"
authors = ["Ideal Network <admin@idealnetwork.io>"]
edition = "2021"
publish = false

[dependencies]
ink = { version = "5.1.1", default-features = false }
idn-contract-lib = { path = "../idn-contract-lib", default-features = false }
noise = { version = "0.9.0", default-features = false} 

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "idn-contract-lib/std",
    "noise/std"
]
ink-as-dependency = []