[package]
name = "sp-consensus-randomness-beacon"
version = "0.0.1-dev"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://idealabs.network"
repository.workspace = true
description = "Primitives for the trustless randomness beacon bridge"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { optional = true, workspace = true }
sp-inherents.workspace = true


[dev-dependencies]
array-bytes = "=6.2.3"
tokio.workspace = true

[features]
default = ["std"]
std = [
	"async-trait",
	"sp-inherents/std",
]
