[package]
name = "sp-consensus-randomness-beacon"
version = "1.0.0-dev"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://idealabs.network"
repository.workspace = true
description = "Primitives for the trustless randomness beacon bridge"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { optional = true, workspace = true }
scale-info = { version = "2.10.0", default-features = false, features = [
	"derive",
] }
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
sp-inherents = { version = "34.0.0", default-features = false }
prost = { version = "0.13.4", default-features = false }
prost-types = { version = "0.13.4", default-features = false }
serde = { version = "1.0.197", features = ["derive"], default-features = false }

# arkworks dependencies
sp-ark-bls12-381 = { git = "https://github.com/paritytech/arkworks-substrate", version = "0.4.2", default-features = false, optional = true }
ark-bls12-381 = { version = "0.4.0", features = ["curve"], default-features = false }
ark-serialize = { version = "0.4.0", features = [ "derive" ], default-features = false }

[build-dependencies]
prost-build = "0.13.4"

[dev-dependencies]
array-bytes = "6.1"
tokio.workspace = true

[features]
default = ["std"]
std = [
	"async-trait",
	"codec/std",
	"sp-inherents/std",
	"scale-info/std",
	"serde/std",
	"prost/std",
	"prost-types/std",
	"ark-bls12-381/std",
	"ark-serialize/std"
]

host-arkworks = [
	"sp-ark-bls12-381/std"
]

# Serde support without relying on std features.
serde = [
	"scale-info/serde",
]
