[package]
name = "sp-consensus-randomness-beacon"
version = "0.0.1-dev"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://idealabs.network"
repository.workspace = true
description = "Primitives for the trustless randomness beacon bridge"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { optional = true, workspace = true }
codec.workspace = true
prost.workspace = true
scale-info.workspace = true
serde = { workspace = true, features = ["derive"] }
sp-inherents.workspace = true

# arkworks dependencies
sp-ark-bls12-381 = { workspace = true, optional = true }
ark-bls12-381.workspace = true
ark-serialize.workspace = true

[dev-dependencies]
array-bytes = "=6.2.3"
tokio.workspace = true

[build-dependencies]
prost-build = "0.13.4"

[features]
default = ["std"]
std = [
	"async-trait",
	"codec/std",
	"scale-info/std",
	"serde/std",
	"sp-inherents/std",
	"prost/std",
	"ark-bls12-381/std",
	"ark-serialize/std",
]
host-arkworks = ["sp-ark-bls12-381"]