name: "Setup Rust Environment"
description: "Sets up Rust toolchains and dependencies"
runs:
  using: "composite"
  steps:
    - name: Install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: "1.85"
        override: true

    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: false

    - name: Setup toolchains
      run: |
        rustup target add wasm32v1-none --toolchain stable-x86_64-unknown-linux-gnu
        rustup target add wasm32v1-none --toolchain nightly-x86_64-unknown-linux-gnu
      shell: bash

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
      shell: bash
