name: "Setup Rust Environment"
description: "Sets up Rust toolchains and dependencies"
inputs:
  rust_version:
    description: "Rust version to install"
    required: false
    default: "1.90"
    type: string
runs:
  using: "composite"
  steps:
    - name: Install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ inputs.rust_version }}
        override: true
        components: rustfmt, clippy, rust-src

    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: false

    - name: Setup toolchains
      run: |
        rustup component add rust-src --toolchain stable-x86_64-unknown-linux-gnu
        rustup target add wasm32v1-none --toolchain stable-x86_64-unknown-linux-gnu
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
        rustup target add wasm32v1-none --toolchain nightly-x86_64-unknown-linux-gnu
      shell: bash

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
      shell: bash

    - name: Cache cargo
      uses: Swatinem/rust-cache@v2

    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.9

    - name: Configure sccache
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
      shell: bash