repos:
  - repo: local
    hooks:
      -   id: fmt
          name: fmt
          description: Format files with cargo fmt.
          entry: cargo +nightly fmt -- --check
          language: system
          files: \.rs$
          args: []