[package]
name = "pallet-idn-manager"
description = "FRAME pallet for managing IDN services."
authors = [
	"Juan Girini <juan@idealabs.network>"
	]
version = "0.0.1"
license = "Apache-2.0"
edition = "2021"
homepage = "https://www.idealabs.network"
repository.workspace = true
publish = false

# [package.metadata.docs.rs]
# targets = ["x86_64-unknown-linux-gnu"]