[relaychain]
<<<<<<< HEAD
default_args = [ "-l=parachain=debug,xcm=trace" ]
=======
default_args = [ "-lxcm=trace,debug" ]
>>>>>>> 18c2ac9 (update chainspec and pop toml)
chain = "paseo-local"

[[relaychain.nodes]]
name = "alice"
rpc_port = 8833
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 2001
name = "idn-consumer-chain"
chain = "idnc-dev"
default_command = "../../target/release/idn-consumer-node"
default_args = [ "-lxcm=trace", "--enable-offchain-indexing=true" ]

[[parachains.collators]]
name = "idn-consumer-alice"
rpc_port = 9944

[[parachains.collators]]
name = "idn-consumer-bob"

[[parachains]]
id = 2000
name = "ideal-network"
chain = "idn-dev"
default_command = "../../target/release/idn-node"
default_args = [ "-lxcm=trace", "--enable-offchain-indexing=true" ]

[[parachains.collators]]
name = "idn-alice"
rpc_port = 9933

[[parachains.collators]]
name = "idn-bob"

[[hrmp_channels]]
sender = 2001
recipient = 2000
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 2000
recipient = 2001
max_capacity = 8
max_message_size = 512