[relaychain]
default_args = [ "-l=parachain=debug,xcm=trace" ]
chain = "paseo-local"

[[relaychain.nodes]]
name = "alice"
rpc_port = 8833
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 4594
name = "idn-consumer-chain"
chain = "idnc-local"
default_command = "../../target/release/idn-consumer-node"
default_args = [ "-lxcm=trace,runtime::contracts=trace,runtime::xcm=trace,xcm::process_instruction::transact=trace,xcm::convert_origin=trace,xcm::origin_conversion=trace,staging_xcm_builder::origin_conversion=trace,pallet-idn-consumer=trace", "--enable-offchain-indexing=true" ]

[[parachains.collators]]
name = "idn-consumer-alice"
rpc_port = 9944

[[parachains.collators]]
name = "idn-consumer-bob"

[[parachains]]
id = 4502
name = "ideal-network"
chain = "idn-local"
default_command = "../../target/release/idn-node"
default_args = [ "-lxcm=trace,runtime::contracts=trace,runtime::xcm=trace,runtime::xcmp=info,pallet-idn-manager=trace,pallet-randomness-beacon=trace", "--enable-offchain-indexing=true" ]

[[parachains.collators]]
name = "idn-alice"
rpc_port = 9933

[[parachains.collators]]
name = "idn-bob"

[[hrmp_channels]]
sender = 4594
recipient = 4502
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 4502
recipient = 4594
max_capacity = 8
max_message_size = 512
