[package]
name = "pallet-drand"
description = "FRAME pallet for bridging to drand."
authors = [
	"Tony Riemer <driemworks@idealabs.network>",
	"Juan Girini <juan@idealabs.network>"
	]
version = "0.0.1"
license = "Apache-2.0"
edition = "2021"
homepage = "https://www.idealabs.network"
repository.workspace = true
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "=3.7.4", default-features = false, features = [
	"derive",
] }
scale-info = { version = "=2.11.6", default-features = false, features = [
	"derive",
] }
serde = {workspace = true, features = ["derive"], default-features = false }
serde_json = { workspace = true, default-features = false }
log = { workspace = true, default-features = false }
hex = { version = "=0.4", features = ["serde"], default-features = false }
sha2 = { version = "=0.10.8", default-features = false }
anyhow = "=1.0.81"
# frame deps
frame-benchmarking = { version = "=38.0.0",  default-features = false, optional = true }
frame-support = { version = "=38.0.0",  default-features = false }
frame-system = { version = "=38.0.0",  default-features = false }
sp-core = { version = "=34.0.0",  default-features = false }
sp-io = { version = "=38.0.0",  default-features = false}
sp-runtime = { version = "=39.0.3",  default-features = false}
# arkworks dependencies
sp-ark-bls12-381 = { git = "https://github.com/paritytech/arkworks-substrate", version = "=0.4.2", default-features = false, optional = true }
ark-bls12-381 = { version = "=0.4.0", features = ["curve"], default-features = false }
ark-serialize = { version = "=0.4.2", features = [ "derive" ], default-features = false }
ark-ff = { version = "=0.4.2", default-features = false }
ark-ec = { version = "=0.4.2", default-features = false }
ark-std = { version = "=0.4.0", default-features = false }
ark-crypto-primitives = { version = "=0.4.0", default-features = false, features = [ "r1cs", "snark" ] } 
ark-scale = { version = "=0.0.11", default-features = false, features = ["hazmat"] }
w3f-bls = { version = "=0.1.4", default-features = false }
sp-keyring = { version = "=39.0.0",  default-features = false }
timelock = { version = "=0.0.1", default-features = false }

[dev-dependencies]
sp-keystore = { version = "=0.40.0",  default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"log/std",
	"sha2/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-keystore/std",
	"sp-keyring/std",
	"sp-runtime/std",
	"serde/std",
	"serde_json/std",
	"hex/std",
	"sp-ark-bls12-381/std",
	"ark-bls12-381/std",
	"ark-serialize/std",
	"ark-ff/std",
	"ark-ec/std",
	"ark-std/std",
	"ark-crypto-primitives/std",
	"ark-scale/std",
	"w3f-bls/std",
	"timelock/std"
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
]
host-arkworks = ["sp-ark-bls12-381"]