[relaychain]
default_image = "docker.io/parity/polkadot:latest"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]

chain = "paseo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 4502

  [[parachains.collators]]
  name = "idn-alice"
  rpc_port = 9933
  command = "../../target/release/idn-node"

  [[parachains.collators]]
  name = "idn-bob"
  command = "../../target/release/idn-node"
