[relaychain]
default_image = "docker.io/parity/polkadot:latest"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
rpc_port = 8833
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 2000
chain = "dev"
default_command = "../../target/release/idn-node"
default_args = [ "-lxcm=trace", "--enable-offchain-indexing=true" ]

[[parachains.collators]]
name = "idn-alice"
rpc_port = 9933

[[parachains.collators]]
name = "idn-bob"
