apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: idn-testnet

resources:
  - ../../base

namePrefix: testnet-eu-

labels:
  - pairs:
      network: testnet
      region: europe-west1

patches:
  # Patch session-keys secret name
  - patch: |-
      - op: replace
        path: /spec/template/spec/volumes/1/secret/secretName
        value: "testnet-eu-collator-session-keys"
    target:
      kind: StatefulSet
      name: idn-collator
  # Patch parachain chain-spec path (args index 4)
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/4
        value: "/chain-specs/idn-paseo.raw.json"
    target:
      kind: StatefulSet
      name: idn-collator
  # Patch relay chain-spec path (args index 19)
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/20
        value: "/chain-specs/paseo.raw.json"
    target:
      kind: StatefulSet
      name: idn-collator
